-- ========================================================
-- 初始化数据脚本
-- 用途：创建系统管理员账号
-- 兼容性：H2 / MySQL / PostgreSQL
-- ========================================================

-- --------------------------------------------------------
-- 管理员账号
-- 用户名: admin
-- 密码: admin123 (BCrypt加密)
-- 邮箱: admin@example.com
--
-- 用途说明：
-- - 系统管理员账号，用于首次登录管理后台
-- - 拥有最高权限，可进行用户管理、系统配置等操作
-- - 生产环境部署后建议立即修改默认密码
-- --------------------------------------------------------

-- BCrypt 加密密码说明：
-- 以下密码使用 BCrypt 算法加密（强度 10轮）
-- admin 密码原文: admin123
-- test  密码原文: test123

-- ========================================================
-- H2 数据库版本（推荐用于开发和测试）
-- ========================================================
-- 使用 MERGE INTO 语法，存在则更新，不存在则插入

MERGE INTO users KEY (id) VALUES (
    1,
    'admin',
    'admin@example.com',
    '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iAt6Z5EHsM8lE9lBOsl',
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

MERGE INTO users KEY (id) VALUES (
    2,
    'test',
    'test@example.com',
    '$2a$10$QxNYNq2qNJ8A3UQw8vYvQOvM5FzKz3Z01Rt.oz4gXLD4dTQFZzCGC',
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

-- ========================================================
-- MySQL 数据库版本（生产环境）
-- ========================================================
-- 取消下方注释使用 MySQL 语法
-- INSERT IGNORE 会忽略主键或唯一键冲突的错误

-- INSERT IGNORE INTO users (id, username, email, password, deleted, created_at, updated_at) VALUES
-- (1, 'admin', 'admin@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iAt6Z5EHsM8lE9lBOsl', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- (2, 'test', 'test@example.com', '$2a$10$QxNYNq2qNJ8A3UQw8vYvQOvM5FzKz3Z01Rt.oz4gXLD4dTQFZzCGC', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ========================================================
-- PostgreSQL 数据库版本（生产环境）
-- ========================================================
-- 取消下方注释使用 PostgreSQL UPSERT 语法

-- INSERT INTO users (id, username, email, password, deleted, created_at, updated_at) VALUES
-- (1, 'admin', 'admin@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iAt6Z5EHsM8lE9lBOsl', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- (2, 'test', 'test@example.com', '$2a$10$QxNYNq2qNJ8A3UQw8vYvQOvM5FzKz3Z01Rt.oz4gXLD4dTQFZzCGC', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
-- ON CONFLICT (id) DO NOTHING;

-- ========================================================
-- 数据库兼容性说明
-- =========================================================
-- | 数据库      | 自增主键语法                                      |
-- |------------|--------------------------------------------------|
-- | H2         | GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY     |
-- | MySQL      | AUTO_INCREMENT                                   |
-- | PostgreSQL | SERIAL 或 GENERATED ALWAYS AS IDENTITY          |
-- ---------------------------------------------------------
-- CURRENT_TIMESTAMP 在所有数据库中通用
